### ISSUE TITLE
Install SQL Server, Import sample DB

### ISSUE THREAD

**Issue by tmccormi** [Vircon/socrates-db-conversion#1]
Install SQL Server 2008 r2 and import the sample DB

**Comment by htuck** [comment]
Have SQL Server up and running; can generate ERD of relevant tables.  Am looking at OpenEMR's demographics fields and finding the corresponding data in Socrates.  Much of it is in the Patient* tables but will also need to track down references, e.g., fetch the actual ethnicity indicated by the code in PatientDetails.EthnicityType.
